app/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView
from django.templatetags.static import static

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('favicon.ico', RedirectView.as_view(url=static('favicon.ico'))),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register_request, name='register'),

    path('profile/', views.profile, name='profile'),
    path('profile/profile_settings', views.profile_settings, name='profile_settings'),
    path('profile/account_settings', views.account_settings, name='account_settings'),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('user_profile/<int:user_id>/', views.user_profile, name='user_profile'),

    path('send_message/<int:receiver_id>/', views.send_message, name='send_message'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/view_message/<int:message_id>/', views.view_message, name='view_message'),
    path('inbox/view_message/<int:message_id>/send_reply', views.send_reply, name='send_reply'),
]

licencjat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app.views import ResetPasswordView


urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('password-reset/', ResetPasswordView.as_view(template_name='logout.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
             auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
             name='password_reset_confirm'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

zapisani_sobie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app.views import ResetPasswordView


urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('password-reset/', ResetPasswordView.as_view(template_name='logout.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
             auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
             name='password_reset_confirm'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
import os
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from datetime import date, timedelta
from multiselectfield import MultiSelectField


################## USER ACCOUNT #####################################################

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username=None, email=None, password=None, **extra_fields):
        if not email:
            raise ValueError('E-mail wymagany.')

        email = self.normalize_email(email) if email else None

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        user = self._create_user(username, email, password, **extra_fields)
        UserProfile.objects.create(user=user)
        return user

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    CHOICES = [
        ('W', 'Kobieta'),
        ('M', 'Mężczyzna'),
        ('O', 'Inne')]

    username = models.CharField(unique=True, max_length=150, blank=True)
    email = models.EmailField(unique=True, max_length=255, blank=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    sex = models.CharField(max_length=1, choices=CHOICES, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    date_of_birth = models.DateField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.date_of_birth:
            today = date.today()
            age = today.year - self.date_of_birth.year - (
                        (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
            profile, created = UserProfile.objects.get_or_create(user=self)
            profile.age = age
            profile.save()


################## USER PROFILE #####################################################


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.userprofile.save()


def user_directory_path(instance, filename):
    user_folder = str(instance.user.username)
    return os.path.join('profile_pics', user_folder, filename)


class UserProfile(models.Model):
    SEX_CHOICES = [
        ('W', 'Kobiety'),
        ('M', 'Mężczyzni'),
        ('O', 'Inni'),
        ('A', 'Wszyscy')]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = CountryField()
    education = models.CharField(max_length=200, blank=True)
    job = models.CharField(max_length=200, blank=True)
    bio = models.CharField(max_length=500, blank=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    followers = models.ManyToManyField(User, related_name='following', blank=True)
    profile_pic = models.ImageField(default='profile_pics/default.png', upload_to=user_directory_path)
    languages = models.CharField(max_length=200, blank=True)
    interests = models.CharField(max_length=500, blank=True)
    min_age_preference = models.PositiveIntegerField(blank=True, null=True)
    max_age_preference = models.PositiveIntegerField(blank=True, null=True)
    sex_preference = models.CharField(max_length=1, choices=SEX_CHOICES, blank=True)


    def save(self, *args, **kwargs):
        try:
            old_profile = UserProfile.objects.get(pk=self.pk)
            if old_profile.profile_pic != self.profile_pic:
                old_profile.profile_pic.delete(save=False)  # Delete the old profile picture from the database
        except UserProfile.DoesNotExist:
            pass
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username


################## WIADOMOŚCI #####################################################


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    subject = models.CharField(max_length=80)
    sent_date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    body = models.TextField()

    font_family = models.CharField(max_length=50, blank=True)
    font_size = models.CharField(max_length=5, blank=True)
    picture = models.CharField(max_length=50, blank=True)


    def __str__(self):
        return self.subject

app/forms.py
from django import forms
from .models import UserProfile, Message, User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django_countries.fields import CountryField

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Login',
                               max_length=150,
                               required=True,
                               widget=forms.TextInput())

    password = forms.CharField(label='Hasło',
                               max_length=150,
                               required=True,
                               widget=forms.PasswordInput(attrs={'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=150,
                               required=True,
                               label='Login',
                               widget=forms.TextInput())

    email = forms.EmailField(required=True,
                             max_length=255,
                             widget=forms.TextInput(),
                             label='E-mail')

    password1 = forms.CharField(max_length=50,
                                required=True,
                                label='Hasło',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    password2 = forms.CharField(max_length=50,
                                required=True,
                                label='Potwierdzenie hasła',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(),
                                 label='Imię')

    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(),
                                label='Nazwisko')

    sex = forms.ChoiceField(required=True,
                            label='Płeć',
                            choices=[
                                ('W', 'Kobieta'),
                                ('M', 'Mężczyzna'),
                                ('O', 'Inne')])

    date_of_birth = forms.DateField(required=True,
                                    label='Data urodzenia',
                                    widget=forms.SelectDateWidget(years=range(1923, 2023)))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'sex', 'date_of_birth']


class UserProfileForm(forms.ModelForm):
    bio = forms.CharField(max_length=500,
                          required=False,
                          label='Opis',
                          widget = forms.Textarea(attrs={'id': 'bio'}))

    country = CountryField(blank_label='Kraj zamieszkania')

    interests = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        label='Zainteresowania',
        required=False,
        choices=[
            ('movies_series', 'Filmy/seriale'),
            ('music', 'Muzyka'),
            ('singing', 'Śpiewanie'),
            ('dancing', 'Taniec'),
            ('books', 'Książki'),
            ('poetics', 'Poezja'),
            ('photography', 'Fotografia'),
            ('painting_drawing', 'Malowanie/rysowanie'),
            ('art', 'Sztuka'),
            ('theater', 'Teatr'),
            ('learning_languages', 'Nauka języków'),
            ('cooking_baking', 'Gotowanie/pieczenie'),
            ('traveling', 'Podróżowanie'),
            ('swimming', 'Pływanie'),
            ('cycling', 'Jazda na rowerze'),
            ('skiing_snowboarding', 'Narty/snowboard'),
            ('football', 'Piłka nożna'),
            ('basketball', 'Koszykówka'),
            ('volleyball', 'Siatkówka'),
            ('tennis', 'Tenis'),
            ('other_sport', 'Inny sport')])

    languages = forms.CharField(
        max_length=200,
        widget=forms.TextInput(),
        label='Znane języki: ',
        required=False)

    education = forms.CharField(
        max_length=200,
        widget=forms.TextInput(),
        label='Wykształcenie: ',
        required=False)

    job = forms.CharField(
        max_length=200,
        widget=forms.TextInput(),
        label='Praca: ',
        required=False)

    sex_preference = forms.ChoiceField(
        label='Interesują mnie: ',
        required=False,
        choices=[
            ('W', 'Kobiety'),
            ('M', 'Mężczyźni'),
            ('O', 'Inni'),
            ('A', 'Wszyscy')])

    min_age_preference = forms.IntegerField(label='Minimum age', required=False)
    max_age_preference = forms.IntegerField(label='Maximum age', required=False)

    profile_pic = forms.ImageField(widget=forms.FileInput())

    class Meta:
            model = UserProfile
            fields = ['bio', 'country', 'interests', 'languages', 'education', 'job', 'sex_preference', 'min_age_preference', 'max_age_preference', 'profile_pic']


class MessageForm(forms.ModelForm):
    subject = forms.CharField(widget=forms.Textarea(attrs={'id': 'message-title',
                                                        'placeholder': 'Tytuł listu ...'}))

    body = forms.CharField(widget=forms.Textarea(attrs={'id': 'message-content',
                                                        'placeholder': 'Treść listu ...'}))

    font_family = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'id': 'font_family'}),
        choices=[("Alex Brush", "Alex Brush"),
                 ("Dancing Script", "Dancing Script"),
                 ("Ephesis", "Ephesis"),
                 ("Great Vibes", "Great Vibes"),
                 ("Monte Carlo", "Monte Carlo"),
                 ("Parisienne", "Parisienne"),
                 ("Petit Formal Script", "Petit Formal Script")])

    font_size = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'id': 'font_size'}),
        choices=[("20", "20px"),
                 ("30", "30px"),
                 ("35", "35px"),
                 ("40", "40px")])

    picture = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'id': 'picture'}),
        choices=[("", "- - -"),
                 ("images/flower1.png", "Kwiatek 1"),
                 ("images/flower2.png", "Kwiatek 2"),
                 ("images/teardrop.png", "Łza"),
                 ("images/kiss.png", "Buziak"),
                 ("images/hair.png", "Kosmyk włosów")])

    class Meta:
        model = Message
        fields = ['picture', 'font_family', 'font_size', 'subject', 'body']

app/templates/account_settings.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="profileinfo">
        <img class="profile_pic" src="{% static 'images/border_img.png' %}" alt='Ramka zdjęcia'>
        <img src="{{ user.userprofile.profile_pic.url }}" alt="Zdjęcie użytkownika {{ user.first_name }}">
            <div style="width: 100%; flex-direction: row; justify-content: space-evenly">
                <h2 style="text-decoration: none">{{ user.username  }}</h2>
                <h2 style="text-decoration: none">{{ user.userprofile.age }} lat</h2>
            </div>
        </div>
    </div>

    <form class="profileinfo" style="width: 50%" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">person</span>Imię:</td>
                <td>{{ user_form.first_name }}</td>
            </tr>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">person</span>Nazwisko:</td>
                <td>{{ user_form.last_name }}</td>
            </tr>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">transgender</span>Płeć:</td>
                <td>{{ user_form.sex }}</td>
            </tr>
            <tr>
                <td class="label"><span class="material-icons">cake</span>Data urodzenia:</td>
                <td>{{ user_form.date_of_birth }}</td>
            </tr>
            <tr>
                <td>
                    <button type="submit" class="button" style="width: 80%; background-color: rgb(179 0 0 / 41%);">
                        <span style="margin-right: 10px; font-size: 20px" class="material-icons">delete</span>
                        Usuń konto
                    </button>
                </td>
                <td>
                    <button type="submit" class="button" style="width: 80%; background-color: rgb(125 170 124 / 79%);">
                        <span style="margin-right: 10px; font-size: 20px" class="material-icons">edit</span>
                        Zapisz zmiany
                    </button>
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/base.html
<html lang="pl">
<head>
    {% load static %}
    {% block title %} {% endblock %}
    <title style="display: none">Zapisani sobie</title>

    <link rel='stylesheet' href='{% static 'style.css' %}' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Dancing+Script&family=Ephesis&family=Great+Vibes&family=Lato:wght@400;700&family=MonteCarlo&family=Parisienne&family=Petit+Formal+Script&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Portal randkowy do wysyłania listów miłosnych.">
</head>
<body>
    {% load static %}
    <nav class="second-nav">
        <ul style="flex-direction: row; align-items: center">
            <li style="margin-right: 5px" class="dropdown-icon"><span class="material-icons" style="font-size: 20px;">translate</span></li>
            <ul style="align-items: flex-end" class="dropdown">
                <li class="dropdown-icon"><span class="material-icons" style="font-size: 23px;">menu</span></li>
                <ul class="dropdown-content">
                    <li><a href="{% url 'app:profile' %}"><span class="material-icons" style="font-size: 20px;">person</span>Konto</a></li>
                    <li><a href="{% url 'app:logout' %}"><span class="material-icons" style="font-size: 20px;">logout</span>Wyloguj się</a></li>
                </ul>
            </ul>
        </ul>
    </nav>
    <nav class="main">
        {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'app:index' %}">Strona główna</a></li>
                <li><a href="{% url 'app:profile_list' %}">Profile</a></li>
                <li><a href="{% url 'app:inbox' %}">Listy</a></li>
            </ul>
        {% else %}
            <ul>
                <li><a href="{% url 'app:index' %}">Strona główna</a></li>
                <li><a href="{% url 'app:login' %}">Zaloguj się</a></li>
                <li><a href="{% url 'app:register' %}">Zarejestruj się</a></li>
            </ul>
        {% endif %}
        <img style="margin-top: -30px;" class="navimage" src="{% static 'images/border_nav.png' %}" alt="Zdjęcie ramki"/>
    </nav>
    <section>
        {% load static %}
        {% block body %}
        {% endblock %}
    </section>
    <footer>
        <div style="width: 50%; font-size: 10px">
            Autorem niniejszego serwisu jest Julia Wróblewska.<br><br>
            Serwis ten stanowi integralną część pracy licencjackiej
            (kierunek: Elektroniczne Przetwarzanie Informacji),
            przygotowanej pod kierunkiem dr. Piotra Śliwińskiego na Wydziale Zarządzania i
            Komunikacji Społecznej Uniwersytetu Jagiellońskiego.
        </div>
        <div style="width: 20%">
            <h4 style="font-size: 10px">Linki do użytej grafiki:</h4>
            <a href="https://www.freepik.com/free-vector/blank-brown-paper-design_13312258.htm#&position=7&from_view=collections" style="font-size: 10px">rawpixel.com</a>
            <a href="https://www.freepik.com/free-vector/premium-quality-banner-collection_4168586.htm#&position=3&from_view=collections" style="font-size: 10px">rawpixel.com</a>
            <a href="https://www.freepik.com/free-photo/wedding-bouquet-with-envelopes_2359674.htm#&position=1&from_view=undefined" style="font-size: 10px">kbza</a>
            <a href="https://www.freepik.com/free-vector/ornamental-vintage-floral-background_5850982.htm#&position=21&from_view=undefined" style="font-size: 10px">1# Freepik</a>
            <a href="https://www.freepik.com/free-photo/floral-branch-with-wedding-invitation_7016080.htm#from_view=detail_alsolike" style="font-size: 10px">2# Freepik</a>
        </div>
    </footer>
</body>
</html>

app/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/password_reset.html
{% extends "base.html" %}
{% block body %}
    <form class="register" style="flex-direction: column" method="POST">
        {% csrf_token %}
        <div>
            <label>Email przypisany do konta:</label>
            <input type="email" name="email" autocomplete="email"
                   maxlength="254" required id="id_email">
        </div>
        <div style="margin-top: 15px">
          <button type="submit" class="button">Zresetuj hasło</button>
        </div>
        <div style="margin-top: 20px; margin-left: 20px">
            <p>Wróć do strony logowania<a href="{% url 'login' %}">Zaloguj się</a></p>
        </div>
    </form>
{% endblock body %}

app/templates/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

app/templates/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <form method="GET">
        <label style="font-size: 20px; margin-bottom: 20px">Filtruj listę użytkowników:</label>
        <div style="margin-bottom: 5px">
            <label for="name"><span class="material-icons" style="font-size: 20px;">person</span>Imię:</label>
            <input type="text" name="name" value="{{ request.GET.name }}">
        </div>

        <div style="margin-bottom: 5px">
            <label for="subject"><span class="material-icons" style="font-size: 20px;">edit</span>Login:</label>
            <input type="text" name="username" value="{{ request.GET.username }}">
        </div>

        <div style="margin-bottom: 20px">
            <label for="sex"><span class="material-icons" style="font-size: 20px;">transgender</span>Płeć:</label>
            <select name="sex">
                <option value="">Wszyscy</option>
                <option value="men" {% if request.GET.status == 'men' %}selected{% endif %}>Mężczyźni</option>
                <option value="women" {% if request.GET.status == 'women' %}selected{% endif %}>Kobiety</option>
            </select>
        </div>
        <button class="button" type="submit">Szukaj</button>
    </form>

    <ul style="width: 70%" class="profiles">
        {% for profile in profiles %}
            <li>
                <a style="text-decoration: none; color: black" href="{% url 'app:user_profile' user_id=profile.id %}">
                    <img class="profile_pic" src="{% static 'images/border_img.png' %}" alt='Ramka zdjęcia'>
                    <img src="{{ profile.profile_pic.url }}" alt="Zdjęcie użytkownika {{ profile.user.username }}">

                    <div style="width: 100%; flex-direction: row; justify-content: space-around; align-items: center; margin-top: 5px">
                        <strong>{{ profile.user.first_name }}</strong>
                        <p>{{ profile.age }} lat</p>
                        <span class="material-icons">favorite</span>
                    </div>
                </a>
            </li>
        {% empty %}
            <li>Brak profili do wyświetlenia.</li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block body %}
    <form class="register" method="POST">
        {% csrf_token %}
        <strong style="text-decoration: underline; margin: 0 10px 10px; width: 100%">Dane konta:</strong>

        {% for field in user_form %}
            <div>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}

        <div style="margin-top: 25px">
            <button type="submit" class="button">Załóż konto</button>
        </div>
        <div style="margin-top: 25px">
            <p>Masz już konto? Zaloguj się tutaj: <a href="/login">Logowanie</a></p>
        </div>
    </form>
{% endblock %}

app/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="profileinfo">
        <img class="profile_pic" src="{% static 'images/border_img.png' %}" alt='Ramka zdjęcia'>
        <img src="{{ profile.userprofile.profile_pic.url }}" alt="Zdjęcie użytkownika {{ profile.first_name }}">
        <div style="width: 100%; flex-direction: row; justify-content: space-evenly; align-items: center">
            <h2 style="text-decoration: none">{{ profile.username  }}</h2>
            <h2 style="text-decoration: none">{{ profile.userprofile.age }} lat</h2>
            <span class="material-icons" style="font-size: 20px;">favorite</span>
        </div>

        <button class="button"><a style="color: black; padding: 0 40px; text-decoration: none" href="{% url 'app:send_message' profile.id %}">Wyślij list</a></button>
    </div>

    <div class="profileinfo" style="width: 50%">
        <table>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">person</span>Imię:</td>
                <td>{{ profile.first_name }}</td>
            </tr>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">person</span>Nazwisko:</td>
                <td>{{ profile.last_name }}</td>
            </tr>
            <tr>
                <td class="label"><span class="material-icons" style="font-size: 20px;">transgender</span>Płeć:</td>
                <td>{{ profile.get_sex_display }}</td>
            </tr>
            {% if profile.userprofile.country %}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">language</span>Kraj:</td>
                    <td>{{ profile.userprofile.get_country_display }}</td>
                </tr>
            {% endif %}
            {% if profile.userprofile.bio %}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">edit</span>Opis:</td>
                    <td>{{ profile.userprofile.bio }}</td>
                </tr>
            {% endif %}
            {% if profile.userprofile.interests %}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">interests</span>Zainteresowania:</td>
                    <td>{{ profile.userprofile.interests }}</td>
                </tr>
            {% endif %}
            {% if profile.userprofile.education %}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">school</span>Edukacja:</td>
                    <td>{{ profile.userprofile.education }}</td>
                </tr>
            {% endif %}
            {% if profile.userprofile.job %}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">work</span>Praca:</td>
                    <td>{{ profile.userprofile.job }}</td>
                </tr>
            {% endif %}
            {% if profile.userprofile.languages%}
                <tr>
                    <td class="label"><span class="material-icons" style="font-size: 20px;">translate</span>Języki:</td>
                    <td>{{ profile.userprofile.languages }}</td>
                </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}

app/templates/view_message.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="sending-message">
        <div class="message">
            <div class="view-message-title" style="font-family: {{ message.font_family }}; font-size: {{ message.font_size }}">{{ message.subject }}</div>
            <div class="view-message-content" style="font-family: {{ message.font_family }}; font-size: {{ message.font_size }}">{{ message.body }}</div>
        </div>

        <div class="next-to-message">
            <div>
                <h1 style="text-decoration: none; margin: 0">List od: {{ message.sender.first_name }}</h1>
                <a href="{{ message.sende.profile.url }}">Zobacz profil użytkownika</a>
            </div>
            <div>
                {% if message.picture %}
                    <p>Użytkownik przesłał Ci:</p>
                    <img style="max-width: 300px; height: auto; margin-top: 15px" src="{% static message.picture %}" alt="Przesłany obiekt">
                {% endif %}
            </div>

            <div>
                <p style="display: inline">Sprawdź <a style="display: inline" href="inbox.html">całą konwersację</a> z użytkownikiem</p>
                <a href="{% url 'app:send_reply' message.id %}" style="padding:0; margin-top: 15px" class="button">Wyślij odpowiedź</a>
            </div>
        </div>
    </div>
{% endblock %}